    const char* input = "int x;\n"
                        "int x;\n"
                        "x = 42;\n"
                        "if (x > 0) {\n"
                        "    int y;\n"
                        "    y = x + 10;\n"
                        "    print y;\n"
                        "}\n"
                        "z = 10;\n"
                        "char test;\n"
                        "test = 123;\n"
                        "x = test + 1;\n"
                        "char foo;\n"
                        "if (foo > 2) {\n"
                        "   int z;\n"
                        "   z = 10;\n"
                        "}\n";